config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'homes#about'
  get 'user/withdrawal' => 'users#withdrawal'
  resources :users, only: %i(show edit update destroy) do
    resource :relationships, only: %i(create destroy)
    #get :follows, params: { on: :member }
    get 'follows' => 'users#follows', as: 'follows'
    get 'followers' => 'users#followers', as: 'followers'
    get 'followings_tweet' => 'tweets#followings_tweet'
    get 'followers_tweet' => 'tweets#followers_tweet'
  end

  post 'new' => 'tweets#new'
  resources :tweets do
    resource :favorites, only: %i(create destroy)
    resources :comments, only: %i(create destroy) do
      post 'favorites/comment_favorites' => 'favorites#comment_create'
      delete 'favorites/comment_destroy' => 'favorites#comment_destroy'
    end
  end

  resources :directmessages, only: [:create]
  resources :rooms, only: %i(create show)
  resources :notifications, only: [:index] do
    delete 'destroy_all'
  end
  resources :activitys, only: [:show]
end

app/models/tweet.rb
# frozen_string_literal: true

class Tweet < ApplicationRecord
  belongs_to :user, optional: true
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :notifications, dependent: :destroy

  # いいねされた時の通知
  def create_notification_favorite!(current_user)
    temp = Notification.where(['active_id = ? and passive_id = ? and tweet_id =? and action = ?', current_user.id, user_id, id, 'favorite'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        tweet_id: id,
        passive_id: user_id,
        action: 'favorite'
      )
      if notification.active_id == notification.passive_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
  end

  # コメントされた時の通知
  def create_notification_comment(current_user, comment_id)
    # 自分以外のコメントuserを取得、通知
    temp_ids = Comment.select(:user_id).where(tweet_id: id).where.not(user_id: current_user.id).distinct
    temp_ids.each do |temp_id|
      notification = current_user.active_notifications.new(
        tweet_id: id,
        comment_id: comment_id,
        passive_id: temp_id.user_id,
        action: 'comment'
      )
      # 自分の投稿に対するコメントの場合は、通知済みとする
      if notification.passive_id == notification.active_id
        notification.checked = true
      end
      notification.save if notification.valid?
    end
   end

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :tweet, presence: true, length: { maximum: 200 }
end

app/controllers/tweets_controller.rb
# frozen_string_literal: true

class TweetsController < ApplicationController
  before_action :authenticate_user!
  def index
    @tweets = Tweet.all
  end

  def show
    @tweet = Tweet.find(params[:id])
    @comment = Comment.new
    @comments = @tweet.comments
    @user = User.find_by(id: @tweet.user_id)
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user_id = current_user.id
    if @tweet.save
      flash[:success] = '投稿しました'
      redirect_to(tweet_path(@tweet)) && return
    else
      flash[:danger] = '投稿に失敗しました'
      render(:new) && return
    end
  end

  def edit
    @tweet = Tweet.find(params[:id])
  end

  def update
    @tweet = Tweet.find(params[:id])
    if @tweet.update(tweet_params)
      flash[:success] = '編集を保存しました'
      redirect_to tweet_path(@tweet)
    else
      flash[:success] = '編集を保存できませんでした'
      render :edit
    end
  end

  def destroy
    tweet = Tweet.find(params[:id])
    tweet.destroy!
    redirect_to user_path(current_user)
  end

  def followings_tweet
    @tweets = Tweet.where(user_id: current_user.followings)
  end

  def followers_tweet
    @tweets = Tweet.where(user_id: current_user.followers)
  end

  private

  def tweet_params
    params.require(:tweet).permit(:tweet, :listener, :genre, :user_id)
  end
end

app/helpers/tweets_helper.rb
# frozen_string_literal: true

module TweetsHelper
end

app/views/tweets/_favorites.html.erb
<% if tweet.favorited_by?(current_user) %>
	<%= link_to tweet_favorites_path(tweet), method: :delete, remote: true do %>
		<i class="glyphicon glyphicon-heart" aria-hidden="true" style="color: red;"></i>
		<%= tweet.favorites.count %>&ensp;
	<% end %>
<% else %>
	<%= link_to tweet_favorites_path(tweet), method: :post,remote: true do %>
		<i class="glyphicon glyphicon-heart" aria-hidden="true"></i>
		<%= tweet.favorites.count %>&ensp;
	<% end %>
<% end %>

app/views/tweets/edit.html.erb
<div class="container-fluid">
	<div class="comment_area">
 		<div class="row">
	        <div class="col-xs-3">
	          <%= render 'users/side_header' %>
	        </div>
			<div class="col-xs-9" style><h1>つぶやき編集</h1>
				<%= form_for(@tweet) do |f| %>
					<def class = "field">
						<div>
							<%= f.label :内容 %><br>
							<%= f.text_area :tweet, autofocus: true, :size=>"100x5" %>
						</div><br>
						<div>
							<%= f.label :聞き手 %><br>
					    	<%= f.select :listener, ["無言、聞き専", "うなづき、あいづち", "対話、会話", "アドバイス、意見が欲しい", "その他"], {include_blank: '選択ボックス'} %>
					    </div><br>
					    <div>
							<%= f.label :ジャンル %><br>
							<%= f.select :genre, ["悩み（軽）", "悩み（重い", "愚痴", "整理するために話をしたい", "その他"], {include_blank: '選択ボックス'} %>
						</div><br>
						<div>
							<%= f.submit "編集を保存する", class: "btn btn-primary" %>
						</div><br>
					</def>
				<% end %>

				<%= link_to "削除する", tweet_path, method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn btn-primary" %>
			</div>
		</div>
	</div>
</div>

app/views/tweets/followers_tweet.html.erb
<div class="container-fluid">
	<div class="comment_area">
  		<div class="row">
			<div class="col-xs-3">
				<%= render "users/side_header" %>
			</div>
			<div class="col-xs-9">
				<table>
					<%= link_to "フォロワー 一覧", user_followers_path(current_user), class: "btn btn-primary" %>
					<table>
						<% @tweets.each do |tweet| %>
						    <div class = "tweet-index">
						    	<div class = "comment-other-than">
									<div  class = "float-left">
									<%= link_to(tweet) do %>
										<%= attachment_image_tag(tweet.user, :profile_image, :fill, 50, 50, format: 'jpeg',fallback: "figure_standing.png", size:'50x50') %>
										<%= tweet.user.name %>
									<% end %>
									</div>
									<div class = "favorite-float">
										<% if tweet.favorited_by?(current_user) %>
											<%= link_to tweet_favorites_path(tweet), method: :delete do %>
												<i class="glyphicon glyphicon-heart" aria-hidden="true" style="color: red;"></i>
												<%= tweet.favorites.count %>&ensp;
											<% end %>
										<% else %>
											<%= link_to tweet_favorites_path(tweet), method: :post do %>
												<i class="glyphicon glyphicon-heart" aria-hidden="true"></i>
												<%= tweet.favorites.count %>&ensp;
											<% end %>
										<% end %>
										<div class = "comment-float">&ensp;<%= "#{tweet.comments.count} コメント" %>&ensp;</div>
									</div>
								</div>
								<div class = "index-comment"><br><%= link_to tweet.tweet, tweet_path(tweet) %><br></div>
							</div>
						<% end %>
					</table>
				</table>
			</div>
		</div>
	</div>
</div>

app/views/tweets/followings_tweet.html.erb
<div class="container-fluid">
	<div class="comment_area">
  		<div class="row">
			<div class="col-xs-3">
				<%= render "users/side_header" %>
			</div>
			<div class="col-xs-9">
				<table>
					<%= link_to "フォロー 一覧", user_follows_path(current_user), class: "btn btn-primary" %>
					<table>
						<% @tweets.each do |tweet| %>
						    <div class = "tweet-index">
						    	<div class = "comment-other-than">
									<div  class = "float-left">
									<%= link_to(tweet) do %>
										<%= attachment_image_tag(tweet.user, :profile_image, :fill, 50, 50, format: 'jpeg',fallback: "figure_standing.png", size:'50x50') %>
										<%= tweet.user.name %>
									<% end %>
									</div>
									<div class = "favorite-float">
										<% if tweet.favorited_by?(current_user) %>
											<%= link_to tweet_favorites_path(tweet), method: :delete do %>
												<i class="glyphicon glyphicon-heart" aria-hidden="true" style="color: red;"></i>
												<%= tweet.favorites.count %>&ensp;
											<% end %>
										<% else %>
											<%= link_to tweet_favorites_path(tweet), method: :post do %>
												<i class="glyphicon glyphicon-heart" aria-hidden="true"></i>
												<%= tweet.favorites.count %>&ensp;
											<% end %>
										<% end %>
										<div class = "comment-float">&ensp;<%= "#{tweet.comments.count} コメント" %>&ensp;</div>
									</div>
								</div>
								<div class = "index-comment"><br><%= link_to tweet.tweet, tweet_path(tweet) %><br></div>
							</div>
						<% end %>
					</table>
				</table>
			</div>
		</div>
	</div>
</div>

app/views/tweets/index.html.erb
<div class="container-fluid">
	<div class="comment_area">
  		<div class="row">
			<div class="col-xs-3">
				<%= render "users/side_header" %>
			</div>
			<div class="col-xs-9">
				<table>
					<% @tweets.each do |tweet| %>
						<div class = "tweet-index">
							<div class = "comment-other-than">
								<div  class = "float-left">
									<%= link_to(tweet.user) do %>
										<%= attachment_image_tag(tweet.user, :profile_image, :fill, 50, 50, format: 'jpeg',fallback: "figure_standing.png", size:'50x50') %>
										<%= tweet.user.name %>
									<% end %>
								</div>
								<div class = "favorite-float">
									<%= render partial: "tweets/favorites", locals: {tweet: tweet} %>
								</div>
								<div class = "comment-float">&ensp;<%= "#{tweet.comments.count} コメント" %>&ensp;
								</div>
							</div>
							<div class = "index-comment"><br><%= link_to tweet.tweet, tweet_path(tweet) %>
							</div><br>
						</div>
					<% end %>
				</table>
			</div>
		</div>
	</div>
</div>

app/views/tweets/new.html.erb
<div class="container-fluid">
	<div class="comment_area">
  		<div class="row">
			<div class="col-xs-3">
				<%= render "users/side_header" %>
			</div>
			<div class="col-xs-9 container text-center">
				<table>
					<%= form_for(@tweet) do |f| %>
						<div class="field">
							<%= f.label :投稿内容 %><br />
							<%= f.text_area :tweet, placeholder: "内容をここに", :size=>"150x15", class:"tweet-textarea input-sm" %><br><br>
						</div>
						<div>
							<a>聞き手へ：　</a>
							<%= f.select :listener, ["無言、聞き専", "うなづき、あいづち", "対話、会話", "アドバイス、意見が欲しい", "その他"], {include_blank: '選択ボックス'}, class: '' %>&ensp;
						</div><br>
						<div>
							<a>ジャンル:　</a>
							<%= f.select :genre, ["悩み（軽)", "悩み（重い)", "愚痴", "整理するために話をしたい", "その他"], {include_blank: '選択ボックス'}, class: '' %>
						</div><br><br>

						<%= f.submit "編集を保存する", class: "btn btn-success" %>
					<% end %>
				</table>
			</div>
		</div>
	</div>
</div>

app/views/tweets/show.html.erb
<div class="container-fluid">
	<div class="comment_area">
  		<div class="row">
			<div class="col-xs-3">
				<%= render "users/side_header" %>
			</div>
			<div class="col-xs-9">
				<table>
					<div class = "tweet-index">
						<div class = "comment-other-than">
							<div class = "float-left">
								<%= link_to(@tweet.user) do %>
									<%= attachment_image_tag(@tweet.user, :profile_image, :fill, 50, 50, format: 'jpeg',fallback: "figure_standing.png",size:"50x50") %>
									<%= @tweet.user.name %>
								<% end %>
							</div>
							<div class = "genre-float">
								&ensp;<%= @tweet.listener %>
							</div>
							<div class = "genre-float">
								&ensp;<%= @tweet.genre %>
							</div>
							<div class = "favorite-float">
								<% if @tweet.favorited_by?(current_user) %>
									<%= link_to tweet_favorites_path(@tweet), method: :delete do %>
										<i class="glyphicon glyphicon-heart" aria-hidden="true" style="color: red;"></i>
										<%= @tweet.favorites.count %>
									<% end %>
								<% else %>
									<%= link_to tweet_favorites_path(@tweet), method: :post do %>
										<i class="glyphicon glyphicon-heart" aria-hidden="true"></i>
										<%= @tweet.favorites.count %>
									<% end %>
								<% end %>
							</div>
						</div>
						<div class = "index-comment"><%= @tweet.tweet %></div>
						<div class = "favorite-float">
							<% if current_user.id == @tweet.user_id %>
								<td><%= link_to "内容を編集する",edit_tweet_path(@tweet), class: "btn btn-primary" %></td>
							<% end %>
						</div>
					</div>
				</table>
				<table class="table">
						<% @tweet.comments.each do |comment| %>
							<tr>
								<td style>
									<%= attachment_image_tag(comment.user, :profile_image, :fill, 50, 50, format: 'jpeg',fallback: "figure_standing.png", size:"50x50") %>
									<%= comment.user.name %>
								</td>
								<td class = "tweet-comment"><%= comment.comment %></td><!-- コメントマークをつける -->
								<td class = "tweet-comment"><%= comment.created_at.strftime('%Y/%m/%d %H:%M') %></td>
								<% if current_user.id == comment.user_id %>
									<td><%= link_to "コメントを削除する", tweet_comment_path(tweet_id: comment.tweet_id, id: comment.id), method: :delete %></td><br><br>
								<% end %>
							</tr>
						<% end %>
				</table>
				<%= form_for [@tweet, @comment] do |f| %>
					<%= f.text_area :comment, placeholder: "コメントをここに", class:"form-control input-sm" %><br>
					<%= f.submit "送信する", class: "btn btn-success" %>
				<% end %>
			</div>
		</div>
	</div>
</div>