config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'homes#about'
  get 'user/withdrawal' => 'users#withdrawal'
  resources :users, only: %i(show edit update destroy) do
    resource :relationships, only: %i(create destroy)
    #get :follows, params: { on: :member }
    get 'follows' => 'users#follows', as: 'follows'
    get 'followers' => 'users#followers', as: 'followers'
    get 'followings_tweet' => 'tweets#followings_tweet'
    get 'followers_tweet' => 'tweets#followers_tweet'
  end

  post 'new' => 'tweets#new'
  resources :tweets do
    resource :favorites, only: %i(create destroy)
    resources :comments, only: %i(create destroy) do
      post 'favorites/comment_favorites' => 'favorites#comment_create'
      delete 'favorites/comment_destroy' => 'favorites#comment_destroy'
    end
  end

  resources :directmessages, only: [:create]
  resources :rooms, only: %i(create show)
  resources :notifications, only: [:index] do
    delete 'destroy_all'
  end
  resources :activitys, only: [:show]
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  acts_as_paranoid
  attachment :profile_image

  has_many :entries
  has_many :directmmessages
  has_many :comments
  has_many :favorites, dependent: :destroy
  has_many :tweets, dependent: :destroy
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'active_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'passive_id', dependent: :destroy

  # フォローする側から見てフォローされる側のUser
  has_many :active_relationships, class_name: 'Relationship', foreign_key: :following_id
  # 中間テーブルを介して「follower」モデルのUser(フォローされた側)を集めることを「followings」と定義
  has_many :followings, through: :active_relationships, source: :follower
  # フォローされる側のUserから見て、フォローしてくる側のUserを(中間テーブルを介して)集める。なので親はfollower_id(フォローされる側)
  has_many :passive_relationships, class_name: 'Relationship', foreign_key: :follower_id
  # 中間テーブルを介して「following」モデルのUser(フォローする側)を集めることを「followers」と定義
  has_many :followers, through: :passive_relationships, source: :following

  # フォローされた時の通知
  def create_notification_follow(current_user)
    temp = Notification.where(['active_id = ? and passive_id = ? and action = ?', current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        active_id: current_user.id,
        passive_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end

  def followed_by?(user)
    passive_relationships.find_by(following_id: user.id).present?
  end

  def unchecked_notifications
    passive_notifications.where(checked: false)
  end

  validates :name, length: { maximum: 20, minimum: 2 }
  validates :introduction, length: { maximum: 200 }
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user! # ログイン済ユーザーのみ許可
  def show
    @user = User.find(params[:id])
    @tweet = @user.tweets
    # dmルーム作成
    @current_user_entry = Entry.where(user_id: current_user.id)
    @user_entry = Entry.where(user_id: @user.id)
    unless @user.id == current_user.id
      @current_user_entry.each do |cu|
        @user_entry.each do |ou|
          if cu.room_id == ou.room_id
            @isroom = true
            @roomid = cu.room_id
          end
        end
      end
      unless @isroom
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      flash[:success] = '編集を保存しました'
      redirect_to user_path(@user)
    else
      flash[:success] = '編集を保存できませんでした'
      render :edit
    end
  end

  def withdrawal
    @user = current_user
  end

  def destroy
    user = current_user
    user.destroy!
    flash[:success] = 'ありがとうございました'
    redirect_to root_path
  end

  def about; end

  def follows
    @users = current_user.followings
  end

  def followers
    @users = current_user.followers
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/users/_side_header.html.erb
<ul class= "header-color">
  <li><%= link_to "Toroba!!", tweets_path, class:"nav header-logo" %></li><br>
    <li> <%= link_to user_path(current_user), class:"header-item header-border" do %>
         <%= attachment_image_tag(current_user, :profile_image, :fill, 50, 50, format: 'jpeg',fallback: "figure_standing.png", size:'50x50' ) %><br><br>
          <%= current_user.name %>
          <% end %><br><br>
    </li>
    <li><%= link_to user_followings_tweet_path(current_user), class:"header-item" do %>
        <i class="glyphicon glyphicon-home home"></i>&emsp;
        <%= current_user.followings.count %>
        <% end %>
    </li>
    <li><%= link_to user_followers_tweet_path(current_user), class:"header-item" do %>
       <i class="glyphicon glyphicon-home home"></i>&emsp;
        <%= current_user.followers.count %>
        <% end %>
    </li>
    <li><%= link_to new_tweet_path, class:"header-item" do %>
        <i class="glyphicon glyphicon-home home"></i>&emsp;つぶやく
        <% end %>
    </li>
    <li>
        <% if current_user.unchecked_notifications.any? %>
            <i class="fa fa-circle" style="color: gold;"></i>
        <% end %>
        <%= link_to notifications_path, class:"header-item header-border" do %>
        <i class="glyphicon glyphicon-home home"></i>&emsp;通知一覧
        <% end %>
    </li>
    <li><%= link_to destroy_user_session_path, method: :delete, class:"header-item" do %>
        <i class="glyphicon glyphicon-home home"></i>&emsp;ログアウト
        <% end %>
    </li>
</ul>

app/views/users/edit.html.erb
<div class="container-fluid">
	<div class="comment_area">
  		<div class="row">
			<div class="col-xs-3">
				<%= render "users/side_header" %>
			</div>
			<div class="col-xs-9 text-center">
				<div class = "user-edit">
					<h1>プロフィール編集</h1>
					<%= form_for(@user) do |f| %>

						<def class = "field">
							<%= f.label :ニックネーム %><br />
							<%= f.text_field :name, autofocus: true, :size=>"90x15" %>
						<div class="field">
							<%= f.label :image %>
							<%= f.attachment_field :profile_image %>
						</div>
						</def>
						<div class="field">
							<%= f.label :メールアドレス %><br />
						    <%= f.email_field :email, autofocus: true, :size=>"90x15" %>
						</div>
						<div class="field">
							<%= f.label :自己紹介 %><br />
							<%= f.text_area :introduction, placeholder: "自己紹介を書きましょう！", :size=>"90%x15" %>
						</div>
							<%= f.submit "編集を保存する", class: "btn btn-primary" %>
					<% end %><br>

					<%= link_to "退会する", user_withdrawal_path, class: "btn btn-danger" %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/users/followers.html.erb
<div class="container-fluid">
	<div class="comment_area">
 		<div class="row">
			<div class="col-xs-3">
				<%= render 'users/side_header' %>
			</div>
			<div class="col-xs-9" style>
				<%#= link_to "ツイート 一覧", user_followers_tweet_path(@users), class: "btn btn-primary" %>
				<table class="table">
					<% @users.each do |user| %>
					   <div class="contents row" >
						<tr>
							<td style>
								<%= link_to(user) do %>
									<%= attachment_image_tag(user, :profile_image, :fill, 50, 50, format: 'jpeg',fallback: "figure_standing.png", size:'50x50') %>
									<%= user.name %>
								<% end %>
							</td>
							<td style><%= user.introduction %></td>
							<td style>
							    <% if user.followers.include?(current_user) %>
									<p><%= link_to 'フォローを外す', user_relationships_path(current_user.id, follower_id: user.id), method: :delete, class: "btn btn-danger" %></p>
								<% else %>
									<p><%= link_to 'フォローする', user_relationships_path(current_user.id, follower_id: user.id), method: :post, class: "btn btn-primary" %></p>
								<% end %>
							</td>
						</tr>
						</div>
					<% end %>
				</table>
			</div>
		</div>
	</div>
</div>

app/views/users/follows.html.erb
<div class="container-fluid">
	<div class="comment_area">
  		<div class="row">
			<div class="col-xs-3">
				<%= render 'users/side_header' %>
			</div>
			<div class="col-xs-9" style>
				<%= link_to "ツイート 一覧", user_followings_tweet_path(@users), class: "btn btn-primary" %>
				<table class="table">
					<% @users.each do |user| %>
					   <div class="contents row" >
						<tr>
							<td style>
								<%= link_to(user) do %>
									<%= attachment_image_tag(user, :profile_image, :fill, 50, 50, format: 'jpeg',fallback: "figure_standing.png", size:'50x50') %>
									<%= user.name %>
								<% end %>
							</td>
							<td style><%= user.introduction %></td>
							<td style>
					        	<% if user.followers.include?(current_user) %>
					              <p><%= link_to 'フォローを外す', user_relationships_path(current_user.id, follower_id: user.id), method: :delete, class: "btn btn-danger" %></p>
					           <% else %>
					              <p><%= link_to 'フォローする', user_relationships_path(current_user.id, follower_id: user.id), method: :post, class: "btn btn-primary" %></p>
					           <% end %>
					   		</td>
						</tr>
						</div>
					<% end %>
				</table>
			</div>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="container-fluid">
  <div class="comment_area">
    <div ng-repeat="data in hoge.chatdata">
      <div class="row">
        <div class="col-xs-3">
          <%= render 'users/side_header' %>
        </div>
        <div class="col-xs-9" style>
          <div class = "introduction">
            <h1><%= @user.name %>さんのマイページ</h1>
              <%= attachment_image_tag(@user, :profile_image, :fill, 50, 50, format: 'jpeg',fallback: "figure_standing.png",size:"50x50") %>&ensp;

              <%= @user.introduction %>
          </div><br>

          <% if current_user == @user %>
            <%= link_to "プロフィール編集", edit_user_path(current_user), class: "btn btn-primary" %>
          <% else %>
            <% if @user.followers.include?(current_user) %>
              <p><%= link_to 'フォローを外す', user_relationships_path(current_user.id, follower_id: @user.id), method: :delete, class: "btn btn-danger" %></p>
            <% else %>
              <p><%= link_to 'フォローする', user_relationships_path(current_user.id, follower_id: @user.id), method: :post, class: "btn btn-primary" %></p>
            <% end %>
          <% end %>

             <!-- DMルームへの記述　-->
          <% unless @user.id == current_user.id %>
            <% if @isroom == true %>
              <%= link_to "DMルームへ", room_path(@roomid), class: "btn btn-primary" %>
            <% else %>
              <%= form_for @room do |f| %>
                <%= fields_for @entry do |entry| %>
                  <%= entry.hidden_field :user_id, :value=> @user.id %>
                <% end %>
                  <%= f.submit "DMルームへ", class: "btn btn-primary" %>
              <% end %>
            <% end %>
          <% end %><br><br>

          <table class="table">
          	<% @tweet.each do |tweet| %>
          	  <tr class = "user_show_tweets">
            		<td>
            			<%= attachment_image_tag(tweet.user, :profile_image, :fill, 50, 50, format: 'jpeg',fallback: "figure_standing.png",size:"50x50") %>
                  <%= @user.name %>&ensp;
            			<%= link_to tweet.tweet, tweet_path(tweet.id) %>
            		</td>
          	  </tr>
            <% end %>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/withdrawal.html.erb
<div class=“row login-row text-center”>
	<div class="col-xs-offset-5" style="margin-top: 20vh; margin-bottom: 20vh;">
			<h3>本当に退会しますか？</h3>

			<div class = "withdrawal_text">退会すると、他のユーザーのつぶやきが見れなくなる他
				<br>今までのいいね、コメント、DMなどが閲覧できなくなります。
				<br>それでも退会する場合は、「退会する」をクリックしてください。
			</div>

			<%= link_to "退会しない", edit_user_path(@user), class: "btn btn-primary"%>&ensp;
			<%= link_to "退会する", user_path(@user), method: :delete, data: {confirm: "本当に退会してもよろしいですか？"}, class: "btn btn-danger" %>
	</div>
</div>